name: match_once
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.0.2
  go_router: ^5.0.5
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  freezed: ^2.1.1
  build_runner: ^2.2.1
  mockito: ^5.3.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  logger: ^1.1.0
  flutter_native_splash: ^2.2.10+1
  url_launcher: ^6.1.6
  image_cropper: ^3.0.1
  image_picker: ^0.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: RocknRoll_One
      fonts:
        - asset: assets/fonts/RocknRoll_One/RocknRollOne-Regular.ttf
    - family: Yusei_Magic
      fonts:
        - asset: assets/fonts/Yusei_Magic/YuseiMagic-Regular.ttf
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/Noto_Sans_JP-Regular.otf
    - family: Zen_Maru_Gothic
      fonts:
        - asset: assets/fonts/Zen_Maru_Gothic/Zen_Maru_Gothic-Regular.ttf
    - family: LINE_Seed_JP
      fonts:
        - asset: assets/fonts/LINE_Seed_JP/OTF/LINESeedJP_A_OTF_Rg.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"